# Generated by Django 5.0.6 on 2024-06-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_evstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evstation',
            name='description',
        ),
    ]
