# Generated by Django 5.0.6 on 2024-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_ev'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev',
            name='email',
            field=models.EmailField(default='nickynikhil1414@gmail.com', max_length=254, unique=True),
        ),
    ]
