# Generated by Django 5.0.6 on 2024-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_ev_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev',
            name='email',
            field=models.EmailField(default='nickynikhil1414@gmail.com', max_length=254),
        ),
    ]
