# Generated by Django 5.0.6 on 2024-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_ev_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
