# Generated by Django 5.0.6 on 2024-06-07 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.AddField(
            model_name='slot',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
